export const WISHLIST_ADD_REQUEST = "WISHLIST_ADD_REQUEST";
export const WISHLIST_ADD_SUCCESS = "WISHLIST_ADD_SUCCESS";
export const WISHLIST_ADD_FAIL = "WISHLIST_ADD_FAIL";

export const WISHLIST_REMOVE_REQUEST = "WISHLIST_REMOVE_ITEM";
export const WISHLIST_REMOVE_SUCCESS = "WISHLIST_REMOVE_SUCCESS";

export const WISHLIST_USER_REQUEST = "WISHLIST_USER_REQUEST";
export const WISHLIST_USER_SUCCESS = "WISHLIST_USER_SUCCESS";
export const WISHLIST_USER_FAIL = "WISHLIST_USER_FAIL";

export const LOAD_WISHLIST_REQUEST = "LOAD_WISHLIST_REQUEST";
export const LOAD_WISHLIST_SUCCESS = "LOAD_WISHLIST_SUCCESS";
export const LOAD_WISHLIST_FAIL = "LOAD_WISHLIST_FAIL";
